name: Sync to Hugging Face Space

on:
  push:
    branches: [main] # Change this if your default branch is 'master'
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true # Set to false if you aren't using Git LFS

      - name: Push to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push https://coderkube:$HF_TOKEN@huggingface.co/spaces/coderkube/Image-Similarity-Search main
